apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  REACT_APP_PARTNER_MANAGER_API_BASE_URL: {{ .Values.pmp_revamp.pms_partner_manager_internal_service_url }}
  REACT_APP_POLICY_MANAGER_API_BASE_URL: {{ .Values.pmp_revamp.pms_policy_manager_internal_service_url }}
  default.conf: |
    server {
      listen       3000;
      server_name  localhost;
      add_header X-Frame-Options DENY;
    
      location / {
          root   /usr/share/nginx/html;
      }
    }
  nginx.conf: |-
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;
      server {
        listen 3000;
        server_name  localhost;
    
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;
    
        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    
        location /v1/partnermanager {
          proxy_pass         {{ .Values.pmp_revamp.pms_partner_manager_internal_service_url }};
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
        }
        location /v1/policymanager {
          proxy_pass         {{ .Values.pmp_revamp.pms_policy_manager_internal_service_url }};
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
        }
    
        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }
