package io.mosip.testrig.pmpui.testcase;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.testrig.pmpui.utility.BaseClass;
import io.mosip.testrig.pmpui.utility.Commons;
import io.mosip.testrig.pmpui.utility.RealTimeReport;

import org.testng.annotations.Listeners;

@Listeners(RealTimeReport.class)
public class AdminPolicyGroupTest extends BaseClass {

	@Test(groups = "PG",dependsOnGroups = "UFCC")
	public void adminPolicyGroupTest() throws InterruptedException {
		 

		test=extent.createTest("AdminPolicyGroupTest", "verify Login");
		Commons.click(test,driver, By.id("policymenugroup"));

		Commons.click(test,driver, By.xpath("//a[@href='#/pmp/resources/policygroup/view']"));
		Commons.click(test,driver, By.xpath("//button[@id='Create Policy Group']"));
		
		Commons.enter(test,driver, By.id("name"), data);
		Commons.enter(test,driver, By.id("desc"), data);
		Commons.click(test,driver, By.xpath("//button[@id='createButton']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		
		
		
		Commons.filter(test,driver, By.id("name"), data);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Edit0"));
		test.log(Status.INFO, "Click on edit");
		Commons.enter(test,driver, By.id("desc"), data + 1);
		Commons.click(test,driver, By.xpath("//button[@id='createButton']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));

		
		

		Commons.filter(test,driver, By.id("name"), data);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Deactivate0"));
		test.log(Status.INFO, "Click on deactive");
		Commons.click(test,driver, By.id("confirmpopup"));
		Commons.click(test,driver, By.id("confirmmessagepopup"));
		
	
		Commons.filter(test,driver, By.id("name"), data);
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Activate0"));
		test.log(Status.INFO, "Click on activate");
		Commons.click(test,driver, By.id("confirmpopup"));
		Commons.click(test,driver, By.id("confirmmessagepopup"));
		
		
		
	}
}
