package io.mosip.testrig.pmpui.testcase;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.testrig.pmpui.utility.BaseClass;
import io.mosip.testrig.pmpui.utility.Commons;
import io.mosip.testrig.pmpui.utility.JsonUtil;
import io.mosip.testrig.pmpui.utility.RealTimeReport;

import org.testng.annotations.Listeners;

@Listeners(RealTimeReport.class)
public class AdminFtmDetailsTest extends BaseClass {
	private static final org.slf4j.Logger logger= org.slf4j.LoggerFactory.getLogger(AdminFtmDetailsTest.class);
	
	@Test(groups = {"FD"},dataProvider = "data-provider-FTM",dependsOnGroups = "RFTM")
	public void adminFtmDetailsTest(String cer) throws InterruptedException {
		
		test=extent.createTest("AdminFtmDetailsTest", "verify Login");
		Commons.click(test,driver, By.xpath("//a[@href='#/pmp/resources/ftmdetails/view']"));

	
		String dropdwnVal=cer.substring(0, cer.indexOf("_", 0));
		String orgName=cer.substring(0, cer.length()-4);
		
	Thread.sleep(3000);
		Commons.filter(test,driver, By.id("make"),By.id("partnerOrganizationName"), data,orgName);
		Thread.sleep(3000);
	//	test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Edit0"));
		Commons.enter(test,driver, By.id("model"), data + 1);
		Commons.click(test,driver, By.xpath("//button[@id='createButton']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));

		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("make"),By.id("partnerOrganizationName"), data,orgName);
		Thread.sleep(3000);
	//	test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		
		Commons.click(test,driver, By.id("Upload Certificate0"));
	//	test.log(Status.INFO, "Upload certificate");
		
		Commons.uploadPartnerCert(driver,By.id("partnerDomain"),dropdwnVal,"\\ftm_cert\\",cer);

		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("make"),By.id("partnerOrganizationName"), data,orgName);
		Thread.sleep(3000);
		Commons.click(test,driver, By.id("ellipsis-button0"));

		Commons.click(test,driver, By.id("View Certificate0"));
	//	test.log(Status.INFO, "view certificate");
		String cert=Commons.getText(driver,By.xpath("//p"));
		logger.info(cert);
		Commons.click(test,driver, By.id("confirmmessagepopup"));		
	
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("make"),By.id("partnerOrganizationName"), data,orgName);
		Thread.sleep(3000);
	//	test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Activate0"));
	//	test.log(Status.INFO, "Click on Activate");
		Commons.click(test,driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("make"),By.id("partnerOrganizationName"), data,orgName);
		Thread.sleep(3000);
	//	test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Deactivate0"));
	//	test.log(Status.INFO, "Click on deactivate");
		Commons.click(test,driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		

	}
}
