package io.mosip.testrig.pmpui.testcase;

import java.awt.AWTException;
import java.io.IOException;

import org.openqa.selenium.By;
import org.testng.annotations.Listeners;
// Generated by Selenium IDE
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.testrig.pmpui.utility.Commons;
import io.mosip.testrig.pmpui.utility.RealTimeReport;
import io.mosip.testrig.pmpui.utility.RegisterBaseClass;

@Listeners(RealTimeReport.class)
public class PartnerLoginAuthCredTest extends RegisterBaseClass {
	private static final org.slf4j.Logger logger= org.slf4j.LoggerFactory.getLogger(RealTimeReport.class);

	@Test(groups = "PLAC", dataProvider = "data-provider-AUTH" ,dependsOnGroups = {"PPM"})
	public void partnerLoginAuthCredTest(String cer) throws InterruptedException, AWTException, IOException{
		//String datetime=Commons.getDateTime();
		test=extent.createTest("PartnerLoginAuthCredTest", "verify Login");
		String dropdwnVal=cer.substring(0, cer.indexOf("_", 0));
		String orgName=cer.substring(0, cer.length()-4);
		
		  

	
		
		driver.findElement(By.id("username")).sendKeys(orgName+data);
		driver.findElement(By.id("password")).sendKeys(orgName+data);
		driver.findElement(By.xpath("//input[@name=\'login\']")).click();
		

		Commons.click(test,driver, By.id("/pmp/resources/policymapping/view"));	
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("requestDetail"),By.id("partnerName"), data,orgName);
		Thread.sleep(3000);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Generate API Key0"));
		

		Commons.enter(test,driver, By.id("apiKeyLabel"),data);

		Commons.click(test,driver, By.id("generateAPIKey"));
		String key=Commons.getText(driver,By.xpath("//p"));	
		logger.info(key);
		Commons.click(test,driver, By.id("confirmmessagepopup"));	
		test.log(Status.INFO, "Click on confirmpopup");
		
	}
}
