package io.mosip.test.pmptest.testcase;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.RealTimeReport;
import org.testng.annotations.Listeners;

@Listeners(RealTimeReport.class)
public class AdminPartnerPolicyMappingTest extends BaseClass {

	@Test(groups = "PPM",dependsOnGroups = "RAC",dataProvider = "data-provider-AUTH" )
	public void adminPartnerPolicyMappingTest(String cer) throws InterruptedException {

		String dropdwnVal=cer.substring(0, cer.indexOf("_", 0));
		String orgName=cer.substring(0, cer.length()-4);
		
		Commons.click(driver, By.xpath("//a[@href='#/pmp/resources/policymapping/view']"));


		
		Commons.filter(driver, By.id("policyName"),By.id("partnerName"), "AUTH"+data,orgName);
		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Manage Policy0"));
		
		Commons.click(driver, By.id("confirmpopup"));
		
		Commons.click(driver, By.id("confirmmessagepopup"));
	}
}
