package io.mosip.test.pmptest.testcase;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;
import io.mosip.test.pmptest.utility.RealTimeReport;
import org.testng.annotations.Listeners;

@Listeners(RealTimeReport.class)
public class AdminAuthPolicyTest extends BaseClass {

	@Test(groups = {"AP"},dependsOnGroups = "PG")
	public void adminAuthPolicyTest() throws InterruptedException{
	
		test=extent.createTest("AdminAuthPolicyTest", "verify Login");
		Commons.click(test,driver, By.id("policymenugroup"));
		test.log(Status.INFO, "clicked on policymenugroup");
		Commons.click(test,driver, By.xpath("//a[@href='#/pmp/resources/authpolicy/view']"));
		
        Commons.click(test,driver, By.xpath("//button[@id='Create Policy']"));
		Thread.sleep(3000);
		Commons.enter(test,driver, By.id("name"), "AUTH"+data);
		Commons.enter(test,driver, By.id("desc"), data);
		Thread.sleep(3000);
		Commons.dropdown(test,driver, By.xpath("//mat-select[@id='policyGroupName']"),data);
		test.log(Status.INFO, "dropdown selected");
		
		
		String policyData;
		try {
			policyData = JsonUtil.JsonObjParsing(Commons.getTestData(),"policyData");
			Commons.enter(test,driver, By.id("policies"), policyData);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		Commons.click(test,driver, By.xpath("//button[@id='createButton']"));
		Thread.sleep(3000);
	
		Commons.click(test,driver, By.id("confirmmessagepopup"));
		
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("name"), "AUTH"+data);
		Thread.sleep(3000);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Edit0"));
		Commons.enter(test,driver, By.id("desc"), data+1);
		
		
		Commons.click(test,driver, By.xpath("//button[@id='createButton']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));

		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("name"), "AUTH"+data);
		Thread.sleep(3000);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Activate0"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		
		
		
		
	}
}
