package io.mosip.test.pmptest.testcase;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;
import io.mosip.test.pmptest.utility.RealTimeReport;
import org.testng.annotations.Listeners;

@Listeners(RealTimeReport.class)
public class AdminSbiDetailsTest extends BaseClass {
	private static final org.slf4j.Logger logger= org.slf4j.LoggerFactory.getLogger(AdminSbiDetailsTest.class);
	@Test(groups = "SD",dataProvider = "data-provider-DEVICE-SBI",dependsOnGroups = "RSD")
	public void adminSbiDetailsTest(String cer) throws Exception {

		String dropdwnVal=cer.substring(0, cer.indexOf("_", 0));
		String orgName=cer.substring(0, cer.length()-4);
		
		test=extent.createTest("AdminSbiDetailsTest", "verify Login");
		Commons.click(test,driver, By.xpath("//a[@href='#/pmp/resources/sbidetails/view']"));
	
		//Commons.filter(test,driver, By.id("swVersion"),By.id("providerId"), data,orgName);
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("swVersion"),data);
		Thread.sleep(3000);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Reject0"));
		test.log(Status.INFO, "Click on reject");

		Commons.click(test,driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("swVersion"),data);
		Thread.sleep(3000);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Edit0"));
		test.log(Status.INFO, "Click on edit");
		Commons.enter(test,driver, By.xpath("//input[@id='swBinaryHash']"), data+1);

		Commons.click(test,driver, By.xpath("//button[@id='createButton']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		Thread.sleep(3000);
		Commons.filter(test,driver, By.id("swVersion"),data);
		Thread.sleep(3000);
		test.log(Status.INFO, "Click on filter");
		Commons.click(test,driver, By.id("ellipsis-button0"));
		Commons.click(test,driver, By.id("Approve0"));
		test.log(Status.INFO, "Click on approve");
		Commons.click(test,driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(test,driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		
	
		
	}
}
