package io.mosip.test.pmptest.testcase;

import java.awt.AWTException;
import java.io.IOException;

import org.openqa.selenium.By;
// Generated by Selenium IDE
import org.testng.annotations.Test;
import io.mosip.test.pmptest.utility.RegisterBaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.ExtentReportUtil;
import io.mosip.test.pmptest.utility.RealTimeReport;
import org.testng.annotations.Listeners;

@Listeners(RealTimeReport.class)
public class PartnerLoginAuthCredTest extends RegisterBaseClass {
	private static final org.slf4j.Logger logger= org.slf4j.LoggerFactory.getLogger(RealTimeReport.class);

	@Test(groups = "PLAC", dataProvider = "data-provider-AUTH" ,dependsOnGroups = {"PPM"})
	public void partnerLoginAuthCredTest(String cer) throws InterruptedException, AWTException{
		//String datetime=Commons.getDateTime();
		
		String dropdwnVal=cer.substring(0, cer.indexOf("_", 0));
		String orgName=cer.substring(0, cer.length()-4);
		
		  ExtentReportUtil.test1 = ExtentReportUtil.reports
                  .createTest("AuthPartnerLogin : " + dropdwnVal + " Orgname : " + orgName);

	
		
		driver.findElement(By.id("username")).sendKeys(orgName+data);
		driver.findElement(By.id("password")).sendKeys(orgName+data);
		driver.findElement(By.xpath("//input[@name=\'login\']")).click();
		

		Commons.click(driver, By.id("/pmp/resources/policymapping/view"));	
		Commons.filter(driver, By.id("requestDetail"),By.id("partnerName"), data,orgName);
		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Generate API Key0"));
		

		Commons.enter(driver, By.id("apiKeyLabel"),data);

		Commons.click(driver, By.id("generateAPIKey"));
		String key=Commons.getText(driver,By.xpath("//p"));	
		logger.info(key);
		Commons.click(driver, By.id("confirmmessagepopup"));	
		ExtentReportUtil.capture();
		try {
			ExtentReportUtil.test1.addScreenCaptureFromPath(ExtentReportUtil.capture());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		  ExtentReportUtil.reports.flush();
		
	}
}
