package io.mosip.test.pmptest.testcase;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;
import io.mosip.test.pmptest.utility.RegisterBaseClass;

public class RegisterTest extends RegisterBaseClass {
	private static final org.slf4j.Logger logger= org.slf4j.LoggerFactory.getLogger(RegisterTest.class);
	@Test(groups = "R",dataProvider = "data-provider" )
	public void registerCRUD(String cer) throws InterruptedException, AWTException{
		String datetime=Commons.getDateTime();
		String dropdwnVal=cer.substring(0, cer.length()-4);
		Commons.click(driver, By.xpath("//a[contains(text(),'Register')]"));
		Commons.enter(driver, By.id("firstName"), datetime);
		Commons.enter(driver, By.id("lastName"), datetime);
		String registerCertKey;
		try {
			registerCertKey = JsonUtil.JsonObjParsing(Commons.getTestData(),"registerCertKey");
			Commons.enter(driver, By.id("organizationName"), dropdwnVal+"_Auto"+registerCertKey);
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	
		
		
		Select select = new Select(driver.findElement(By.id("user.attributes.partnerType")));
		
		
				select.selectByValue(dropdwnVal+"_PROVIDER");
		
		Commons.enter(driver, By.id("address"), datetime);
		Commons.enter(driver, By.id("email"), datetime+"@automationlabs.com");
		Commons.enter(driver, By.id("phoneNumber"), "9178338765");
		Commons.selOption(driver, By.id("user.attributes.langCode"), "English");
		
		
		Commons.enter(driver, By.id("username"),datetime);
		Commons.enter(driver, By.id("password"), Commons.getUnique());
		Commons.enter(driver, By.id("password-confirm"),Commons.getUnique());
		Commons.click(driver, By.xpath("//input[@type='submit']"));
		
		Commons.click(driver, By.xpath("(//button[@id='createButton'])[1]"));
		

		Commons.uploadPartnerCert(driver,By.id("partnerDomain"),dropdwnVal,"\\partner_cert\\",cer);

		
		
//		Commons.dropdown(driver, By.id("partnerDomain"), By.id(dropdwnVal)
//				);
//
//		Commons.clickAction(driver, By.xpath("//*[@type='button']"));
//		
//		String filePath=null;;
//		try {
//			filePath = System.getProperty("user.dir") + "\\partner_cert\\"+cer ;
//		} catch (Exception e) {
//			
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		  
//		
//		
//		StringSelection ss = new StringSelection(filePath);
//
//
//		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);
//
//		Robot robot = new Robot();
//
//		robot.delay(250);
//		robot.keyPress(KeyEvent.VK_ENTER); robot.keyRelease(KeyEvent.VK_ENTER);
//		robot.keyPress(KeyEvent.VK_CONTROL); robot.keyPress(KeyEvent.VK_V);
//		robot.keyRelease(KeyEvent.VK_V); robot.delay(250);
//		robot.keyRelease(KeyEvent.VK_CONTROL); robot.keyPress(KeyEvent.VK_ENTER);
//		robot.delay(250); robot.keyRelease(KeyEvent.VK_ENTER); robot.delay(250);
//		Commons.click(driver, By.id("createButton"));
//		Commons.click(driver, By.id("confirmmessagepopup"));
//		
		Commons.click(driver, By.xpath("(//button[@id='createButton'])[2]"));
		
		
		String cert=Commons.getText(driver,By.xpath("//p"));
		logger.info(cert);
		Commons.click(driver, By.id("confirmmessagepopup"));		
	}
}
