package io.mosip.test.pmptest.testcase;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;

public class UploadFtmCaCertTest extends BaseClass {

	@Test(groups = "UFCC")
	public void UploadFtmCaCertCRUD() throws InterruptedException, AWTException {

		Commons.click(driver, By.xpath("//a[@href='#/pmp/resources/uploadcacert/upload']"));
		Commons.click(driver, By.xpath("//span[contains(text(),'Upload CA Certificate')]"));
		Thread.sleep(30); 

		Commons.dropdown(driver, By.xpath(
				"/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/mat-form-field/div/div[1]/div/mat-select/div/div[1]/span"),
				By.xpath("/html/body/div[2]/div[2]/div/div/div/mat-option[1]/span"));
		Thread.sleep(30);
         
		
		
		Commons.click(driver,By.xpath("//div[@class='custom-file-input']"));
		
		
		//Commons.click(driver, By.xpath("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]"));
		
		driver.findElement(By.xpath("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]")).sendKeys("D:\\Mosip_Automation_Test\\MOSIP_FUNCTIONAL_TESTS\\AdminUI\\admin-ui\\admintest\\certificate\\ftmca.cert");
		
		
		
		
		
		String filePath = System.getProperty("user.dir") + "\\certificate\\ftmca.cert";
		//driver.findElement(By.xpath("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]")).sendKeys(filePath);
		
		WebElement browse = driver.findElement(By.xpath("//*[@id=\"myDiv\"]/mat-card/mat-card-content/div/div/input[1]"));
		Thread.sleep(300);
		Commons.click(driver, By.xpath("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]"));
		Thread.sleep(300);
		
		browse.sendKeys("D:\\Mosip_Automation_Test\\MOSIP_FUNCTIONAL_TESTS\\AdminUI\\admin-ui\\admintest\\certificate\\ftmca.cert");
		Thread.sleep(30);
		
		driver.findElement(By.xpath("//input[@placeholder='Upload Your File *']")).sendKeys("D:\\Mosip_Automation_Test\\MOSIP_FUNCTIONAL_TESTS\\AdminUI\\admin-ui\\admintest\\certificate\\ftmca.cert");
		
		
		//Commons.click(driver, By.xpath("//input[@class='browseInput']"));
		//Commons.enter(driver, By.xpath("//input[@class='browseInput']"), "D:\\Mosip_Automation_Test\\MOSIP_FUNCTIONAL_TESTS\\AdminUI\\admin-ui\\admintest\\certificate\\ftmca.cert");
		
		driver.get("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]");
			driver.findElement(By.xpath("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]")).click();

		
		
		
		   StringSelection ss = new StringSelection(filePath);
		   
		   Commons.enter(driver, By.xpath("/html/body/app-root/app-parent/div/mat-sidenav-container/mat-sidenav-content/cert-upload/div/div/div[2]/mat-card/mat-card-content/div/div/input[1]"), filePath);
		   Thread.sleep(200);
			
		   
		   /*
			 * Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);
			 * 
			 * Robot robot = new Robot();
			 * 
			 * robot.delay(250);
			 * 
			 * 
			 * robot.keyPress(KeyEvent.VK_ENTER); robot.keyRelease(KeyEvent.VK_ENTER);
			 * robot.keyPress(KeyEvent.VK_CONTROL); robot.keyPress(KeyEvent.VK_V);
			 * robot.keyRelease(KeyEvent.VK_V); robot.delay(250);
			 * robot.keyRelease(KeyEvent.VK_CONTROL); robot.keyPress(KeyEvent.VK_ENTER);
			 * robot.delay(250); robot.keyRelease(KeyEvent.VK_ENTER); robot.delay(250);
			 */

	}
}
