package io.mosip.test.pmptest.testcase;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;

public class ZDeviceDetailsTest extends BaseClass {

	private static final org.slf4j.Logger logger= org.slf4j.LoggerFactory.getLogger(ZDeviceDetailsTest.class);
	@Test(groups = "DD",dataProvider = "data-provider-partner")
	public void deviceDetailsCRUD(String cer) throws InterruptedException {

		String dropdwnVal=cer.substring(0, cer.length()-4);
		Commons.click(driver, By.xpath("//a[@href='#/pmp/resources/devicedetails/view']"));

		Commons.click(driver, By.xpath("//button[@id='Create Device']"));
		String registerCertKey;
		try {
			registerCertKey = JsonUtil.JsonObjParsing(Commons.getTestData(),"registerCertKey");

			Commons.dropdown(driver, By.id("deviceProviderId"),dropdwnVal+"_Auto"+registerCertKey);
			
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		/*
		//Commons.dropdown(driver, By.id("deviceProviderId"));
		Commons.dropdown(driver, By.id("deviceTypeCode"));
		Commons.dropdown(driver, By.id("deviceSubTypeCode"));
		Commons.enter(driver, By.xpath("//input[@placeholder='Make']"), data);
		Commons.enter(driver, By.xpath("//input[@placeholder='Model']"), data);
		Commons.click(driver, By.xpath("//button[@id='createButton']"));

//Need to change this Line after Aravind Provide Id
		Commons.click(driver, By.xpath("//span[contains(text(),'Ok')]"));

		Commons.click(driver, By.id("Filter"));
		Commons.filter(driver, By.id("make"), data);
		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Approve0"));

//Need to change these 2 Lines after Aravind Provide Id
		Commons.click(driver, By.xpath("//span[contains(text(),'Yes')]"));
		Commons.click(driver, By.xpath("//span[contains(text(),'Ok')]"));

		
		Commons.filter(driver, By.id("make"), data);
		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Edit0"));

		Commons.dropdown(driver, By.xpath("//mat-select[@placeholder='SBIVersion']"));

		Commons.click(driver, By.xpath("//button[@id='createButton']"));
		Commons.click(driver, By.xpath("//button[@id='confirmmessagepopup']"));  
		Commons.click(driver, By.xpath("//span[contains(text(),'Cancel')]"));
		
		Commons.filter(driver, By.id("make"), data);
		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Reject0"));
		Commons.click(driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(driver, By.xpath("//button[@id='confirmmessagepopup']"));
		
		*/
		
		Commons.dropdown(driver, By.id("deviceTypeCode"),By.id("Face"));
		Thread.sleep(3000);
		Commons.dropdown(driver, By.id("deviceSubTypeCode"),By.id("Full face"));
		Commons.enter(driver, By.xpath("//input[@placeholder='Make']"), data);
		Commons.enter(driver, By.xpath("//input[@placeholder='Model']"), data);
		Commons.click(driver, By.xpath("//button[@id='createButton']"));

//Need to change this Line after Aravind Provide Id
		Commons.click(driver, By.xpath("//span[contains(text(),'Ok')]"));

		Commons.click(driver, By.id("Filter"));
		Commons.filter(driver, By.id("make"), data);

		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Edit0"));
		Commons.enter(driver, By.xpath("//input[@placeholder='Model']"), data + 1);
		Commons.click(driver, By.xpath("//button[@id='createButton']"));
		Commons.click(driver, By.xpath("//span[contains(text(),'Ok')]"));

		Commons.filter(driver, By.id("make"), data);
		
		Commons.click(driver, By.id("ellipsis-button0"));
		
		Commons.click(driver, By.id("Upload Certificate0"));
	
		
		Commons.uploadPartnerCert(driver,By.id("partnerDomain"),dropdwnVal,"\\partner_cert\\",cer);

		Commons.filter(driver, By.id("make"), data);

		Commons.click(driver, By.id("ellipsis-button0"));

		Commons.click(driver, By.id("View Certificate0"));

		String cert=Commons.getText(driver,By.xpath("//p"));
		logger.info(cert);
		Commons.click(driver, By.id("confirmmessagepopup"));		
	

		Commons.filter(driver, By.id("make"), data);

		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Activate0"));
		
		Commons.click(driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(driver, By.xpath("//button[@id='confirmmessagepopup']"));
		

		Commons.filter(driver, By.id("make"), data);

		Commons.click(driver, By.id("ellipsis-button0"));
		Commons.click(driver, By.id("Reject0"));
		
		Commons.click(driver, By.xpath("//button[@id='confirmpopup']"));
		Commons.click(driver, By.xpath("//button[@id='confirmmessagepopup']"));

	}
}
