apiVersion: v2
name: pmp-reactjs-ui
description: A Helm chart for MOSIP pmp reactJS UI module
type: application
version: 1.3.0-dp.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - pmp
maintainers:
  - email: info@mosip.io
    name: MOSIP
