package io.mosip.test.admintest.testcase;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.paulhammant.ngwebdriver.NgWebDriver;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
public class DeviceTest extends BaseClass{
   @Test(groups = "D")
  public void deviceCRUD() throws InterruptedException {
	
	   Commons.click(driver,By.id("admin/resources"));
	   Commons.click(driver,By.id("/admin/resources/devices"));
	   Commons.click(driver,By.id("Create Device"));
	   
	   
	   Commons.enter(driver, By.id("name"),data);
	   Commons.enter(driver, By.id("serialNumber"),data);

	   Commons.enter(driver, By.id("macAddress"),"1.1234");
 
	   Commons.enter(driver, By.id("ipAddress"),"2.2345");
	   Commons.enter(driver, By.id("validity"),"3/3/2023");
      
    Commons.dropdown(driver,By.id("deviceSpecId"));
     Commons.dropdown(driver,By.id("zone"));
      Commons.dropdown(driver,By.id("regCenterId"));
      

      	Commons.createRes(driver);
     	Commons.filter(driver, By.id("name"), data);
     	

     	Commons.editRes(driver,data+1,By.id("name"));
     	Commons.filter(driver, By.id("name"), data+1);
     	
     	Commons.activate(driver);
     	Commons.editRes(driver,data+2,By.id("name"));
     	Commons.filter(driver, By.id("name"), data+2);
     	Commons.deactivate(driver);
     	Commons.decommission(driver);
    }
  }
