package io.mosip.test.admintest.testcase;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;
import io.mosip.test.pmptest.utility.PropertiesUtil;

public class HolidaysTest extends BaseClass{
 
  @Test(groups = "H")
  public void holidaysCRUD() throws Exception {
	String listofholidays="admin/masterdata/holiday/view";
	String holidayDate=JsonUtil.JsonObjParsing(Commons.getTestData(),"holidayDate");
    Commons.click(driver,By.xpath("//a[@href='#/admin/masterdata']"));
   
    Commons.click(driver,By.id(listofholidays));
    Commons.click(driver,By.id("Create"));
    
  
    Commons.enter(driver,By.id("holidayName"),data);
    Commons.enter(driver,By.id("holidayDesc"),data);
    Commons.enter(driver,By.id("holidayDate"),holidayDate);
    Commons.dropdown(driver,By.id("locationCode"));
        
    
    Commons.create(driver);
	Commons.filter(driver, By.id("holidayName"), data);
	

	Commons.edit(driver,data+1,By.id("holidayName"));
	Commons.filter(driver, By.id("holidayName"), data+1);
	
	Commons.activate(driver);
	Commons.edit(driver,data+2,By.id("holidayName"));
	Commons.filter(driver, By.id("holidayName"), data+2);
	Commons.deactivate(driver);

    }
}
