package io.mosip.test.admintest.testcase;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.pmptest.utility.BaseClass;
import io.mosip.test.pmptest.utility.Commons;
import io.mosip.test.pmptest.utility.JsonUtil;
public class MachineTest extends BaseClass{
  @Test(groups = "M")
  public void machineCRUD() throws Exception {
	  String holidayDateCenter=JsonUtil.JsonObjParsing(Commons.getTestData(),"holidayDateCenter");
	  String publicKey=JsonUtil.JsonObjParsing(Commons.getTestData(),"publicKey");

	  String signPublicKey=JsonUtil.JsonObjParsing(Commons.getTestData(),"signPublicKey");
	  
	  Commons.click(driver,By.id("admin/resources"));
    Commons.click(driver,By.xpath("//a[@href='#/admin/resources/machines']"));
    Commons.click(driver,By.id("Create Machine"));
    
    Commons.enter(driver,By.id("name"),data);
    Commons.enter(driver,By.id("serialNumber"),"1234567");
    Commons.enter(driver,By.id("macAddress"),"1.2.3.4.5.6");
    Commons.enter(driver,By.id("ipAddress"),"2.3.4.5.6");
    Commons.enter(driver,By.id("validity"),holidayDateCenter);
    Commons.dropdown(driver,By.id("machineSpecId"));
    Commons.enter(driver,By.id("publicKey"),publicKey);
    		
    		Commons.enter(driver,By.id("signPublicKey"),signPublicKey);
    				Commons.dropdown(driver,By.id("zone"));
    Commons.dropdown(driver,By.id("regCenterId"));
    
    
    
   	Commons.createRes(driver);
 	Commons.filter(driver, By.id("name"), data);
 	

 	Commons.editRes(driver,data+1,By.id("name"));
 	Commons.filter(driver, By.id("name"), data+1);
 	
 	Commons.activate(driver);
 	Commons.editRes(driver,data+2,By.id("name"));
 	Commons.filter(driver, By.id("name"), data+2);
 	Commons.deactivate(driver);
 	Commons.decommission(driver);
  }
}
