apiVersion: v2
name: pmp-ui-v2
description: A Helm chart for MOSIP pmp uiv2 UI module
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - pmp
maintainers:
  - email: info@mosip.io
    name: MOSIP
