package io.mosip.testrig.pmprevampui.utility;

public class GlobalConstants {

	public static final String isLogoutButtonDisplayed = "Verify if logout button is display on dashboard screen.";
	public static final String isLoginPageDisplayed = "Verify if login page is displayed after clicking on logout button in dashboard page."; 
	public static final String isRegisterPageTitleDisplayed = "Verify if register page is displayed after clicking on register button in login page.";
	public static final String isFirstNameTextBoxDisplayed = "Verify if first name textbox is displayed in register page.";
	public static final String isLastNameTextBoxDisplayed = "Verify if last name textbox is displayed in register page.";
	public static final String isOrganizationNameDisplayed = "Verify if organization name textbox is displayed in register page.";
	public static final String isPartnerTypeDropdownDisplayed = "Verify if partner type dropdown is displayed in register page.";
	public static final String isAddressTextBoxDisplayed = "Verify if address textbox is displayed in register page.";
	public static final String isEmailTextBoxDisplayed = "Verify if email id textbox is displayed in register page.";
	public static final String isPhoneNumberTextboxDisplayed = "Verify if phone number textbox is displayed in register page.";
	public static final String isNotificationLanguageDropdownDisplayed = "Verify if notification language dropdown is displayed in register page.";
	public static final String isUsernameTextBoxDisplayed = "Verify if username textbox is displayed in register page.";
	public static final String isPasswordTextBoxDisplayed = "Verify if password textbox is displayed in register page.";
	public static final String isPasswordConfirmTextBoxDisplayed = "Verify if confirm password textbox is displayed in register page.";
	public static final String isSubmitButtonDisplayed = "Verify if submit button is displayed";   
	public static final String isSelectPolicyGroupPopUpDisplayed = "Verify if select policy group is displayed after click on submit button";
	public static final String isSubmitButtonSelectPolicyGroupPopUpDisplayed = "Verify if submit button is displayed in select policy group pop up in dashboard page.";
	public static final String isTermsAndConditionsPopUppDisplayed = "Verify if term and condition pop up displayed";
	public static final String isProceedButtonDisplayed = "Verify if proceed button is displayed.";
	public static final String isPartnerCertificateTitleDisplayed = "Verify if partner certificate title is displayed";
	public static final String isPartnerCertificatePageDisplayed = "Verify if partner certificate page is displayed";
	public static final String isUploadPartnerCertificatePopUpDisplayed = "Verify if upload partner certificate pop up is displayed";
	public static final String isSucessMessageDisplayed = "Verify if Partner certificate for Authentication Partner is uploaded successfully.";
	public static final String isPoliciesTitleDisplayed = "Verify if policies title is displayed";
	public static final String isPoliciesPageDisplayed = "Verify if policies page is displayed after click on policies title";
	public static final String isPartnerIdDropdownDisplayed = "Verify if partner id dropdown is displayed.";
	public static final String isPolicyNameDropdownDisplayed = "Verify if policy name dropdown displayed";
	public static final String isPolicySubmittedSuccessfullyDisplayed = "Verify if Policy Submitted Successfully displayed";
	public static final String isNoDataTextDisplaed = "Verify if Policy dropdown no policy data text displayed";
	public static final String isPolicyEmptyTableIsDisplayed = "Verify if policies empty table displayed";
	public static final String isAuthenticationServicesDisplayed = "Verify if authentication services title is displayed";
	
	public static final String isRedirectUri2TextBoxDisplayed = "Verify if authentication services title is displayed";
	public static final String isLogoUriempty = "verify if Enter Logo URI is precent";
	public static final String isInvalidLogoUriErrorVissible = "verify if Invalid Logo Uri Error message is issiblet";

	public static final String isCreateOIDCClientDisplayed = "Verify if create OIDC client is displayed";
	public static final String isEnterValidLogoUriTextDisplayed = "Verify if enter valid logo uri text displayed";
	public static final String isEnterRedirectUriTextDisplayed = "Verify if enter valid redirect uri text displayed";
	public static final String isAutherisationCodeTextDisplayed = "Verify if Authrisation code is selected by default displayed";
	public static final String isPolicyGroupHeaderTextDisplayed = "Verify if policy group header text displayed";
	public static final String isPolicyNameHeaderTextDisplayed = "Verify if policy name header text displayed";
	public static final String isOIDCClientNameHeaderTextDisplayed = "Verify if oidc client name header text displayed";
	public static final String isCreatedDateHeaderTextDisplayed = "Verify if create data header text displayed";
	public static final String isStatusHeaderTextDisplayed = "Verify if status header text displayed";
	public static final String isOIDCClientIDHeaderTextDisplayed = "Verify if oidc client header text displayed";
	public static final String isActionHeaderTextDisplayed = "Verify if action header text displayed";
	public static final String isRequestPolicyEnabled = "Verify if request policy button enabled";
	public static final String isGenerateAPIKeyDisplayed = "Verify if generate api key text displayed.";
	public static final String isApiKeyHeaderTextDisplayed = "Verify if api key header Text displayed";
	public static final String isListOfPolicyRequestedTextDisplayed = "Verify if list of policy requested text displayed";
	public static final String isNextPageDisplayed = "Verify if next page for policy requested  displayed";
	public static final String isPreviousPageDisplayed = "Verify if Previous page for policy requested  displayed";
	public static final String isPendingForApprovalDisplayed = "Verify if pending for approval text displayed";
	public static final String isPartnerIdTextDisplayed = "Verify if partner id text displayed";
	public static final String isPartnerIdDescAscIcon = "Verify if partner Asending decending icon displayed";
	public static final String isPartnerTypeDescAscIcon = "Verify if partner type Asending decending icon displayed";
	public static final String isPolicyGroupNameDescAscIcon = "Verify if policy group name type Asending decending icon displayed";
	public static final String isPolicyNameDescAscIcon = "Verify if policy name Asending decending icon displayed";
	public static final String isCreatedDateTimeDescAscIcon = "Verify if created date time Asending decending icon displayed";
	public static final String isSubTitleHomeDisplayed = "Verify if subtitle home displayed";
	public static final String isSubTitleDisplayed  = "Verify if subtitle displayed";
	public static final String isBackArrow = "Verify if back arrow icon displayed";
	public static final String isViewPolicyTitle = "Verify if view policy title displayed";
	public static final String isSelectPolicyGroupViewMoreAndLess = "Verify if select policy group view more and less is displayed";
	public static final String isSelectPolicyGroupSubmitDisabled = "Verify if select policy group submit disabled";
	public static final String isOriginalCertificateDownloadPopupDisplayed = "Verify if Originally uploaded CA signed certificate downloaded successfully displayed";
	public static final String isMosipCertificateDownloadPopupDisplayed = "Verify if mosip signed certificate downloaded successfully displayed";
	public static final String iReUploadPartnerCertificateTextDisplayed = "Verify if Re-Upload partner certificate title displayed";
	public static final String isReUploadPartnerCertificateSubTextDisplayed = "Verify if please select all fields and upload the certificate text displayed";
	public static final String isInvalidCertFormatePopupDisplayed = "Verify if The certificate uploaded is not in the correct format. Only certificates having format .cer or .pem is allowed for upload text displayed";
	public static final String TABLE = "</table>";
	public static final String TR = "</tr>";
	public static final String IGNORED_SUBSET_STRING = "feature not supported;Service not deployed";
	public static final String EMAILABLEREPORT2NAME = "emailable.report2.name";
	public static final String TRTR = "</th></tr>";
	public static final String SKIPPED = "Skipped";
	public static final String KNOWN_ISSUE_SUBSET_STRING = "known issue;";
	public static final String TRCLASS = "<tr class=\"";
	public static final String colspan = " colspan=\"";
	public static final String TDTR = "</td></tr>";
	public static final String KNOWN_ISSUES_STRING = "known issue";
	public static final String NUMATTN = "num attn";
	public static final String FEATURE_NOT_SUPPORTED = "feature not supported";
	public static final String SERVICE_NOT_DEPLOYED = "Service not deployed";
	public static final String SERVICE_NOT_DEPLOYED_MESSAGE = "Service not deployed. Hence skipping the testcase";
	public static final String KNOWN_ISSUES = "known issue. Hence skipping the testcase";
}
